# SPDX-FileCopyrightText: KDE Contributors
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/ki8n': '@latest-kf6'
    'third-party/libbtrfsutil': '@latest'

Options:
  in-source-build: False
  test-before-installing: False
  run-tests: False
  run-cppcheck: True
  cppcheck-arguments: '--enable=warning,style,performance'
  require-cppcheck-clean: True
